#!/usr/bin/env bash
set -euo pipefail

# ── 1. Install Docker ──────────────────────────────────────────────────────────
echo "[1/4] Installing Docker..."
sudo curl -fsSL https://get.docker.com | sh

# ── 2. Create working directory ────────────────────────────────────────────────
echo "[2/4] Creating /opt/remnanode..."
sudo mkdir -p /opt/remnanode
cd /opt/remnanode

# ── 3. Write docker-compose.yml ───────────────────────────────────────────────
echo "[3/4] Writing docker-compose.yml..."
sudo tee docker-compose.yml > /dev/null <<'EOF'
services:
  remnanode:
    container_name: remnanode
    hostname: remnanode
    image: remnawave/node:latest
    network_mode: host
    restart: always
    cap_add:
      - NET_ADMIN
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    environment:
      - NODE_PORT=2222
      - SECRET_KEY="eyJub2RlQ2VydFBlbSI6Ii0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLVxuTUlJQmxqQ0NBVHlnQXdJQkFnSUhBWGRpY0ZHUktEQUtCZ2dxaGtqT1BRUURBakF3TVM0d0xBWURWUVFERENWblxuT1cxVU5YbG9USFZpUmtkek1HTjJNamRDVURKNVVtUnhTbDlDWVRWelZIbGtUREI1TUI0WERUSTJNRFF4TlRFMlxuTWpnek9Wb1hEVEk1TURReE5URTJNamd6T1Zvd09URTNNRFVHQTFVRUF4TXVZalZPVGt0V1lqbDFaM0JLVUVSRlxuWlZnek9HWk9ZM1J2Y0V0SUxXaFpiVXBoVjBwbWFtdERSek0yY2twRFRUQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1xuU000OUF3RUhBMElBQkRwcjEyKzg4cll2Y1ZGNVhBWEhVSHlnNklFTFphNnJMUHhlVXNmZ3pQRktFWHQ3aWlSWVxuczhGenV5M0hzRk5zZUp1M0V1emNNQnBScklWWjhhSk1Rb21qT0RBMk1Bd0dBMVVkRXdFQi93UUNNQUF3RGdZRFxuVlIwUEFRSC9CQVFEQWdXZ01CWUdBMVVkSlFFQi93UU1NQW9HQ0NzR0FRVUZCd01CTUFvR0NDcUdTTTQ5QkFNQ1xuQTBnQU1FVUNJUURDdHlrMHNVd1JKNHp2NytDM0VKRHRITzdoQWFaZ003VENNSjZYT0NPSFpnSWdXa1Y2YUtid1xuc1lXVjVWM2NNSktnMlZ2T1lOTFcxSGI4SThUS1VPL3RHb289XG4tLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tIiwibm9kZUtleVBlbSI6Ii0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlHSEFnRUFNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQkcwd2F3SUJBUVFna21mR3hQVm1iTmttdTZuUVxuWmpCNFFYZ21qRTQxcUt3Z25FQmFIaFlsaTUraFJBTkNBQVE2YTlkdnZQSzJMM0ZSZVZ3RngxQjhvT2lCQzJXdVxucXl6OFhsTEg0TXp4U2hGN2U0b2tXTFBCYzdzdHg3QlRiSGlidHhMczNEQWFVYXlGV2ZHaVRFS0pcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0iLCJjYUNlcnRQZW0iOiItLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS1cbk1JSUJjekNDQVJpZ0F3SUJBZ0lCQVRBS0JnZ3Foa2pPUFFRREFqQXdNUzR3TEFZRFZRUUREQ1ZuT1cxVU5YbG9cblRIVmlSa2R6TUdOMk1qZENVREo1VW1SeFNsOUNZVFZ6Vkhsa1REQjVNQjRYRFRJMU1URXhOakEzTXpBME9Gb1hcbkRUTTFNVEV4TmpBM016QTBPRm93TURFdU1Dd0dBMVVFQXd3bFp6bHRWRFY1YUV4MVlrWkhjekJqZGpJM1FsQXlcbmVWSmtjVXBmUW1FMWMxUjVaRXd3ZVRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk40L3RVem9cbnBEby9QbzlkcTdzdTBvMG9HOXcvSC9melhnTHNhTDJKcFU5Smt4MVRrZll0Mmc3ZXFJa0krUXI3eHFRbGdvYVdcbnZyZ2lJZ284dGdsbnl0eWpJekFoTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnS0Vcbk1Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRQzNSL0lTeFd5U1FpempZTmRSMHFQUjFYRXZKQmhtMnVJdDFBdjdcbmdaeldoQUloQVBVR2dQVTVPcm14WkEwaW5RSzk4c2E0Zll0QVdJWFZJN1JyNGlxUlQ0QnFcbi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0iLCJqd3RQdWJsaWNLZXkiOiItLS0tLUJFR0lOIFBVQkxJQyBLRVktLS0tLVxuTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUExUVBYUlRsTzRGSFA4T1dVRVIzK1xuVTJ4Zlg5ZjdpaUpHdXFqTGowVVlkTXlkZzJDdkdNVTVUaDFoVUV6eWhJRUxCdSs1NWF3T2FWME1lblV1R3dldlxuSkpPcC9WbExTUktIcEpJTlhHa1VYWllPaU1EWXNYWWZvOU5tNkFEempNNW0rVjdCOWh1eHFwODRnc2dIYUNRaVxuOG01VGtYQW1adEpwelV3aHAvaHcwZ2FrUkkyZTVaTHZaWm8zNUhIUW0wbFFvNlpCSjFRU0R0MU9JMjRJNFVoUFxucEVZQTAvSHlsdi9GcWh3VW04b2pKSHV0VjJuL21iUmpSOTd1T2k0TWoxNjRZRCsySVpmVmw2VWVpTi9aN0FGbVxuYzNheER4OWVDUUc5eEpkN1JGUURHejVBRmtaS05VcmlKMGU4RVlkNmpJaXc2QnZBRDljL3lvQTUwWVZvVXZmWVxub1FJREFRQUJcbi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLVxuIn0="
EOF

# ── 4. Start the container and follow logs ─────────────────────────────────────
echo "[4/4] Starting remnanode..."
sudo docker compose up -d
sudo docker compose logs -f -t
